server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.14:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: http://192.168.50.14:${server.port}
    hostname: http://192.168.50.14


spring:
  application:
    name: eureka-client
  datasource:
    primary:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/my_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
    secondary:
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource





