server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.14:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: http://192.168.50.14:${server.port}
    hostname: http://192.168.50.14

spring:
  application:
    name: eureka-service
feign:
  hystrix:
    enabled: true